"""Root CLI for Meeting-ASR workflows."""

from __future__ import annotations

import click
import sys
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as package_version

import typer
from typer.completion import completion_init
from typer.main import get_command

from app.commands import (
    agent,
    completion,
    config,
    doctor,
    lexicon,
    oss,
    paths,
    project,
    voiceprint,
)
from app.completion_helpers import complete_cli_language
from app.presentation.cli.help import render_help
from app.presentation.cli.i18n import configure_cli_language
from app.presentation.cli.output import configure_cli_output
from app.presentation.cli.typer_context import HELP_CONTEXT, MeetingAsrTyper
from app.utils import configure_logging

completion_init()

ROOT_HELP = """Project-based CLI for DashScope meeting transcription workflows.

Quick start:
  meeting-asr project run <video>
  meeting-asr project review <project-id-or-path>
  meeting-asr project transcript show <project-id-or-path> --kind corrected

Inspect state:
  meeting-asr project list
  meeting-asr paths
  meeting-asr doctor

Agent discovery:
  meeting-asr agent-guide
  meeting-asr commands --json
  meeting-asr version --json
"""

app = MeetingAsrTyper(
    add_completion=False,
    add_help_option=False,
    context_settings=HELP_CONTEXT,
    invoke_without_command=True,
    no_args_is_help=False,
    pretty_exceptions_enable=False,
    help=ROOT_HELP,
)


def _version_callback(value: bool) -> None:
    """
    Print package version and exit when requested.

    Args:
        value: Whether the eager ``--version`` flag was passed.

    Returns:
        None.
    """
    if not value:
        return
    typer.echo(f"meeting-asr {_installed_version()}")
    raise typer.Exit()


def _installed_version() -> str:
    """
    Return the installed package version.

    Returns:
        Package version, or a local-development fallback.
    """
    try:
        return package_version("meeting-asr")
    except PackageNotFoundError:
        return "0.0.0+local"


@app.callback()
def root(
    ctx: typer.Context,
    version: bool = typer.Option(
        False,
        "--version",
        callback=_version_callback,
        is_eager=True,
        help="Show version and exit.",
    ),
    no_color: bool = typer.Option(
        False, "--no-color", help="Disable colored Rich output."
    ),
    verbose: bool = typer.Option(
        False, "--verbose", "-v", help="Enable verbose diagnostic logs."
    ),
    lang: str | None = typer.Option(
        None,
        "--lang",
        help="Help language: auto, en, or zh.",
        autocompletion=complete_cli_language,
    ),
    help_: bool = typer.Option(
        False, "--help", "-h", help="Show this message and exit."
    ),
) -> None:
    """Configure root command options."""
    try:
        configure_cli_language(lang)
    except ValueError as exc:
        raise click.BadParameter(str(exc), param_hint="--lang") from exc
    configure_cli_output(no_color=no_color, verbose=verbose)
    configure_logging(verbose=verbose)
    if help_ or ctx.invoked_subcommand is None:
        render_help(get_command(app), ())
        raise typer.Exit()


def help_command(ctx: typer.Context) -> None:
    """Show help for the root command or a nested command."""
    command_path = tuple(ctx.args)
    command = _resolve_help_command(get_command(app), command_path)
    render_help(command, command_path)


def _resolve_help_command(
    root_command: click.Command, command_path: tuple[str, ...]
) -> click.Command:
    """
    Resolve a nested command path for ``meeting-asr help``.

    Args:
        root_command: Root Click command generated by Typer.
        command_path: Nested command names.

    Returns:
        Click command whose help should be printed.
    """
    command = root_command
    for name in command_path:
        if not isinstance(command, click.Group):
            raise click.UsageError(
                f"`{' '.join(command_path)}` is not a command group."
            )
        child = command.commands.get(name)
        if child is None:
            raise click.UsageError(
                f"No such command for help: {' '.join(command_path)}"
            )
        command = child
    return command


app.command("doctor", context_settings=HELP_CONTEXT)(doctor.command)
app.command("agent-guide", context_settings=HELP_CONTEXT)(agent.agent_guide_command)
app.command("commands", context_settings=HELP_CONTEXT)(agent.commands_command)
app.command("version", context_settings=HELP_CONTEXT)(agent.version_command)
app.command(
    "help",
    context_settings={
        **HELP_CONTEXT,
        "allow_extra_args": True,
        "ignore_unknown_options": True,
    },
)(help_command)
app.add_typer(
    config.app,
    name="config",
    help="Manage global XDG configuration.",
    context_settings=HELP_CONTEXT,
)
app.add_typer(
    project.app,
    name="project",
    help="Manage project-based transcription workflows.",
    context_settings=HELP_CONTEXT,
)
app.add_typer(
    voiceprint.app,
    name="voiceprint",
    help="Manage the cross-project voiceprint registry.",
    context_settings=HELP_CONTEXT,
)
app.add_typer(
    lexicon.app,
    name="lexicon",
    help="Manage the cross-project correction lexicon.",
    context_settings=HELP_CONTEXT,
)
app.add_typer(
    oss.app,
    name="oss",
    help="Upload, sign, and configure OSS objects.",
    context_settings=HELP_CONTEXT,
)
app.add_typer(
    completion.app,
    name="completion",
    help="Generate or install shell completion scripts.",
    context_settings=HELP_CONTEXT,
)
app.command("paths", context_settings=HELP_CONTEXT)(paths.command)


def main() -> None:
    """Run the root Typer app."""
    if agent.root_version_json_requested(sys.argv[1:]):
        from app.presentation.cli.json_output import emit_json

        emit_json(agent.version_envelope())
        return
    app()


if __name__ == "__main__":
    main()
