"""Localized help rendering for Meeting-ASR-owned help command."""

from __future__ import annotations

from collections.abc import Iterable

import click
import typer

from app.presentation.cli.i18n import current_cli_language

ROOT_INTRO = {
    "en": "Project-based CLI for DashScope meeting transcription workflows.",
    "zh": "用于 DashScope 会议转写的项目化 CLI。",
}
ROOT_SECTIONS = {
    "en": (
        ("Quick start", ("meeting-asr project run <video>", "meeting-asr project review <project-id-or-path>")),
        (
            "Inspect state",
            ("meeting-asr project list", "meeting-asr paths", "meeting-asr doctor"),
        ),
    ),
    "zh": (
        ("快速开始", ("meeting-asr project run <video>", "meeting-asr project review <project-id-or-path>")),
        ("常用查看", ("meeting-asr project list", "meeting-asr paths", "meeting-asr doctor")),
    ),
}
LABELS = {
    "en": {"usage": "Usage", "description": "Description", "arguments": "Arguments", "options": "Options", "commands": "Commands"},
    "zh": {"usage": "用法", "description": "说明", "arguments": "参数", "options": "选项", "commands": "命令"},
}
COMMAND_ZH = {
    (): "用于 DashScope 会议转写的项目化 CLI。",
    ("doctor",): "检查运行依赖和全局配置。",
    ("help",): "显示 root 或嵌套命令帮助。",
    ("paths",): "显示 Meeting-ASR 配置、数据、缓存和存储路径。",
    ("config",): "管理全局 XDG 配置。",
    ("project",): "管理项目化转写流程。",
    ("project", "list"): "列出默认或指定项目库里的项目。",
    ("project", "transcript"): "查看项目转写产物。",
    ("project", "transcript", "list"): "列出一个项目的转写产物。",
    ("project", "transcript", "show"): "显示一个项目转写产物的内容。",
    ("voiceprint",): "管理跨项目声纹库。",
    ("voiceprint", "list"): "列出全局声纹库里的说话人。",
    ("lexicon",): "管理跨项目纠错词库。",
    ("lexicon", "list"): "列出本地词库词条。",
    ("oss",): "上传、签名和配置 OSS 对象。",
    ("completion",): "生成或安装 shell completion 脚本。",
}
OPTION_ZH = {
    "--version": "显示版本并退出。",
    "--no-color": "关闭 Rich 彩色输出。",
    "--verbose": "显示详细诊断日志。",
    "--lang": "设置 help 语言：auto、en 或 zh。",
    "--projects-dir": "指定项目库目录。",
    "--json": "输出机器可读 JSON。",
    "--plain": "输出稳定的制表符分隔文本。",
    "--kind": "选择产物类型，例如 auto、plain、named、corrected、srt。",
    "--help": "显示帮助并退出。",
}
OPTION_EN = {
    "--projects-dir": "Project store directory.",
}


def render_help(command: click.Command, command_path: tuple[str, ...]) -> None:
    """
    Render localized help for a Click command.

    Args:
        command: Click command generated by Typer.
        command_path: Nested command path after ``meeting-asr help``.

    Returns:
        None.
    """
    lang = current_cli_language()
    ctx = click.Context(command, info_name=" ".join(("meeting-asr", *command_path)))
    lines = [_usage_block(command, ctx, lang)]
    description = _command_description(command, command_path, lang)
    if description:
        lines.extend(_section(lang, "description", (description,)))
    if command_path == ():
        lines.extend(_root_sections(lang))
    lines.extend(_argument_block(command, lang))
    lines.extend(_option_block(command, lang))
    lines.extend(_command_block(command, command_path, lang))
    typer.echo("\n".join(lines).rstrip())


def _usage_block(command: click.Command, ctx: click.Context, lang: str) -> str:
    """Build the usage line."""
    pieces = " ".join(command.collect_usage_pieces(ctx))
    suffix = f" {pieces}" if pieces else ""
    return f"{LABELS[lang]['usage']}:\n  {ctx.info_name}{suffix}"


def _section(lang: str, key: str, values: Iterable[str]) -> list[str]:
    """Build a titled help section."""
    lines = ["", f"{LABELS[lang][key]}:"]
    lines.extend(f"  {value}" for value in values)
    return lines


def _root_sections(lang: str) -> list[str]:
    """Build root example sections."""
    lines: list[str] = []
    for title, commands in ROOT_SECTIONS[lang]:
        lines.extend(["", f"{title}:"])
        lines.extend(f"  {command}" for command in commands)
    return lines


def _argument_block(command: click.Command, lang: str) -> list[str]:
    """Build argument rows."""
    rows = [param for param in command.params if isinstance(param, click.Argument)]
    if not rows:
        return []
    values = [f"{param.human_readable_name}    {_argument_required_text(param, lang)}" for param in rows]
    return _section(lang, "arguments", values)


def _option_block(command: click.Command, lang: str) -> list[str]:
    """Build option rows."""
    options = [param for param in command.params if isinstance(param, click.Option)]
    values = [_option_line(param, lang) for param in options]
    if not any("--help" in option.opts for option in options):
        values.append(_help_option_line(lang))
    return _section(lang, "options", values)


def _command_block(command: click.Command, command_path: tuple[str, ...], lang: str) -> list[str]:
    """Build subcommand rows for a group."""
    if not isinstance(command, click.Group):
        return []
    values = []
    for name, child in command.commands.items():
        if child.hidden:
            continue
        path = (*command_path, name)
        values.append(f"{name:<12} {_command_description(child, path, lang)}")
    return _section(lang, "commands", values)


def _option_line(option: click.Option, lang: str) -> str:
    """Build one option row."""
    names = ", ".join((*option.opts, *option.secondary_opts))
    metavar = _option_metavar(option)
    left = f"{names} {metavar}".strip()
    return f"{left:<28} {_option_help(option, lang)}"


def _help_option_line(lang: str) -> str:
    """Build the implicit help option row."""
    return f"{'--help':<28} {OPTION_ZH['--help'] if lang == 'zh' else 'Show this message and exit.'}"


def _option_metavar(option: click.Option) -> str:
    """Return an option value placeholder when needed."""
    if getattr(option, "is_flag", False):
        return ""
    return option.metavar or option.type.name.upper()


def _option_help(option: click.Option, lang: str) -> str:
    """Return localized option help."""
    if lang == "zh":
        for name in option.opts:
            if name in OPTION_ZH:
                return OPTION_ZH[name]
    for name in option.opts:
        if name in OPTION_EN:
            return OPTION_EN[name]
    return option.help or ""


def _command_description(command: click.Command, command_path: tuple[str, ...], lang: str) -> str:
    """Return localized command description."""
    if lang == "zh":
        return COMMAND_ZH.get(command_path) or command.short_help or command.help or ""
    if command_path == ():
        return ROOT_INTRO["en"]
    return command.short_help or command.help or ""


def _argument_required_text(argument: click.Argument, lang: str) -> str:
    """Return a short required/optional label for one argument."""
    if argument.required:
        return "必填" if lang == "zh" else "required"
    return "可选" if lang == "zh" else "optional"
