"""Localized Rich help rendering for Meeting-ASR-owned CLI help."""

from __future__ import annotations

import click
from rich import box
from rich.console import Console
from rich.padding import Padding
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from app.presentation.cli.i18n import current_cli_language
from app.presentation.cli.output import cli_console

ROOT_INTRO = {
    "en": "Project-based CLI for DashScope meeting transcription workflows.",
    "zh": "用于 DashScope 会议转写的项目化 CLI。",
}
ROOT_SECTIONS = {
    "en": (
        ("Quick start", ("meeting-asr project run <video>", "meeting-asr project review <project-id-or-path>")),
        ("Inspect state", ("meeting-asr project list", "meeting-asr paths", "meeting-asr doctor")),
    ),
    "zh": (
        ("快速开始", ("meeting-asr project run <video>", "meeting-asr project review <project-id-or-path>")),
        ("常用查看", ("meeting-asr project list", "meeting-asr paths", "meeting-asr doctor")),
    ),
}
LABELS = {
    "en": {"usage": "Usage", "arguments": "Arguments", "options": "Options", "commands": "Commands"},
    "zh": {"usage": "用法", "arguments": "参数", "options": "选项", "commands": "命令"},
}
COMMAND_ZH = {
    (): "用于 DashScope 会议转写的项目化 CLI。",
    ("doctor",): "检查运行依赖和全局配置。",
    ("help",): "显示 root 或嵌套命令帮助。",
    ("paths",): "显示 Meeting-ASR 配置、数据、缓存和存储路径。",
    ("config",): "管理全局 XDG 配置。",
    ("project",): "管理项目化转写流程。",
    ("project", "list"): "列出默认或指定项目库里的项目。",
    ("project", "transcript"): "查看项目转写产物。",
    ("project", "transcript", "list"): "列出一个项目的转写产物。",
    ("project", "transcript", "show"): "显示一个项目转写产物的内容。",
    ("voiceprint",): "管理跨项目声纹库。",
    ("voiceprint", "list"): "列出全局声纹库里的说话人。",
    ("lexicon",): "管理跨项目纠错词库。",
    ("lexicon", "list"): "列出本地词库词条。",
    ("oss",): "上传、签名和配置 OSS 对象。",
    ("completion",): "生成或安装 shell completion 脚本。",
}
OPTION_ZH = {
    "--version": "显示版本并退出。",
    "--no-color": "关闭 Rich 彩色输出。",
    "--verbose": "显示详细诊断日志。",
    "--lang": "设置 help 语言：auto、en 或 zh。",
    "--projects-dir": "指定项目库目录。",
    "--json": "输出机器可读 JSON。",
    "--plain": "输出稳定的制表符分隔文本。",
    "--kind": "选择产物类型，例如 auto、plain、named、corrected、srt。",
    "--help": "显示帮助并退出。",
}
OPTION_EN = {
    "--projects-dir": "Project store directory.",
}


def render_help(command: click.Command, command_path: tuple[str, ...]) -> None:
    """
    Render localized help for a Click command with Rich panels.

    Args:
        command: Click command generated by Typer.
        command_path: Nested command path after ``meeting-asr help``.

    Returns:
        None.
    """
    lang = current_cli_language()
    ctx = click.Context(command, info_name=" ".join(("meeting-asr", *command_path)))
    console = cli_console()
    console.print(Padding(_usage_text(command, ctx, lang), 1))
    body = _help_body(command, command_path, lang)
    if body:
        console.print(Padding(body, (0, 1, 1, 1)))
    _print_arguments_panel(command, lang, console)
    _print_options_panel(command, lang, console)
    _print_commands_panel(command, command_path, lang, console)


def _usage_text(command: click.Command, ctx: click.Context, lang: str) -> Text:
    """Build the localized usage line."""
    pieces = " ".join(command.collect_usage_pieces(ctx))
    suffix = f" {pieces}" if pieces else ""
    text = Text(f"{LABELS[lang]['usage']}: ", style="bold")
    text.append(f"{ctx.info_name}{suffix}", style="bold")
    return text


def _help_body(command: click.Command, command_path: tuple[str, ...], lang: str) -> Text:
    """Build the localized command help body."""
    lines = [_command_description(command, command_path, lang)]
    if command_path == ():
        lines.extend(_root_help_lines(lang))
    return Text("\n".join(line for line in lines if line).strip())


def _root_help_lines(lang: str) -> list[str]:
    """Build root quick-start help lines."""
    lines: list[str] = []
    for title, commands in ROOT_SECTIONS[lang]:
        lines.extend(["", f"{title}:"])
        lines.extend(f"  {command}" for command in commands)
    return lines


def _print_arguments_panel(command: click.Command, lang: str, console: Console) -> None:
    """Print positional arguments when a command has them."""
    rows = [param for param in command.params if isinstance(param, click.Argument)]
    if not rows:
        return
    table = _table()
    table.add_column(style="cyan", no_wrap=True)
    table.add_column(style="green", no_wrap=True)
    for argument in rows:
        table.add_row(argument.human_readable_name, _argument_required_text(argument, lang))
    console.print(Panel(table, title=LABELS[lang]["arguments"], border_style="dim"))


def _print_options_panel(command: click.Command, lang: str, console: Console) -> None:
    """Print option rows in a scan-friendly Rich panel."""
    options = [param for param in command.params if isinstance(param, click.Option)]
    if not any("--help" in option.opts for option in options):
        options.append(_implicit_help_option(lang))
    if not options:
        return
    table = _table()
    table.add_column(style="cyan", no_wrap=True)
    table.add_column(style="magenta", no_wrap=True)
    table.add_column(ratio=1)
    for option in options:
        table.add_row(_option_names(option), _option_metavar(option), _option_help(option, lang))
    console.print(Panel(table, title=LABELS[lang]["options"], border_style="dim"))


def _print_commands_panel(command: click.Command, command_path: tuple[str, ...], lang: str, console: Console) -> None:
    """Print child commands in a scan-friendly Rich panel."""
    if not isinstance(command, click.Group):
        return
    commands = [(name, child) for name, child in command.commands.items() if not child.hidden]
    if not commands:
        return
    table = _table()
    table.add_column(style="cyan", no_wrap=True)
    table.add_column(ratio=1)
    for name, child in commands:
        table.add_row(name, _command_description(child, (*command_path, name), lang))
    console.print(Panel(table, title=LABELS[lang]["commands"], border_style="dim"))


def _table() -> Table:
    """Create a compact help table matching Typer's default visual density."""
    return Table(show_header=False, expand=True, box=box.SIMPLE_HEAVY, pad_edge=False, padding=(0, 1))


def _implicit_help_option(lang: str) -> click.Option:
    """Build the implicit help option for groups that rely on Click defaults."""
    return click.Option(["--help"], is_flag=True, help=OPTION_ZH["--help"] if lang == "zh" else "Show this message and exit.")


def _option_names(option: click.Option) -> str:
    """Return display names for one option."""
    return ", ".join((*option.opts, *option.secondary_opts))


def _option_metavar(option: click.Option) -> str:
    """Return an option value placeholder when needed."""
    if getattr(option, "is_flag", False):
        return ""
    return option.metavar or option.type.name.upper()


def _option_help(option: click.Option, lang: str) -> str:
    """Return localized option help."""
    if lang == "zh":
        for name in option.opts:
            if name in OPTION_ZH:
                return OPTION_ZH[name]
    for name in option.opts:
        if name in OPTION_EN:
            return OPTION_EN[name]
    return option.help or ""


def _command_description(command: click.Command, command_path: tuple[str, ...], lang: str) -> str:
    """Return localized command description."""
    if lang == "zh":
        return COMMAND_ZH.get(command_path) or command.short_help or command.help or ""
    if command_path == ():
        return ROOT_INTRO["en"]
    return command.short_help or command.help or ""


def _argument_required_text(argument: click.Argument, lang: str) -> str:
    """Return a short required or optional label for one argument."""
    if argument.required:
        return "必填" if lang == "zh" else "required"
    return "可选" if lang == "zh" else "optional"
